export const theme = {
    primaryFontFamily: "'Space Mono', monospace",
    secondaryFontFamily: "'Nunito Sans', sans-serif",
    backgroundColor: "#121212",
    secondaryBackgroundColor: "#1B1920",
    surfaceColor: "#272727",
    surfaceColorHover: "#2E2E2E",
    textColor: "#d6d6d6",
    primaryColor: "#BA49FF",
    secondaryColor: "#856ABD",
    borderColor: "#2F2F2F",
    screen: {
        mobile: "480px",
        tablet: "768px",
        laptop: "1024px",
        desktop: "1024px",
    },
    size: {
        smaller: "0.25rem",
        small: "0.5rem",
        medium: "1rem",
        large: "2rem",
        larger: "4rem",
    },
};
